name: CB-Heads
version: 2.4
main: Enes5519\PlayerHead\PlayerHead
api: [3.0.0]
author: Enes5519
fixer: WolfTubeTM
forker: Wertzui123

permissions:
  playerhead:
    default: op
    children:
      cb-heads.gethead:
        default: op
      cb-heads.gethead.bypass:
        default: op
      cb-heads.blacklist:
        default: op
      cb-heads.spawn:
        default: true
      cb-heads.kill:
        default: true
