name: CB-Heads
version: 2.0
main: Enes5519\PlayerHead\PlayerHead
api: [3.0.0]
author: Enes5519
fixer: WolfTubeTM
forker: Wertzui123

permissions:
  playerhead:
    default: op
    children:
      playerhead.give:
        default: op
      playerhead.spawn:
        default: op
      playerhead.attack:
        default: op
